[build]
    command = "gatsby build"
    publish = "public"
[dev]
    command = "gatsby develop"

[[plugins]]
  # Installs the Lighthouse Build Plugin for all deploy contexts
  package = "@netlify/plugin-lighthouse"

 [plugins.inputs]
    output_path = "reports/lighthouse.html"
